<?xml version="1.0"?>
<!-- parts-list2.xml -->
<!DOCTYPE parts-list [
<!ELEMENT parts-list    (component+, part+)>
<!ELEMENT component     (name, partref)>
<!ATTLIST component     component-id ID #REQUIRED>

<!ELEMENT name          (#PCDATA)>

<!ELEMENT partref       EMPTY>
<!ATTLIST partref       refid IDREFS #REQUIRED>

<!ELEMENT part          (name)>
<!ATTLIST part          part-id ID #REQUIRED>
]>

<parts-list>
    <component component-id="T-65">
        <name>X-wing</name>
        <partref refid="WG BL CP AM"/>
    </component>
    <component component-id="TIE-LN">
        <name>TIE</name>
        <partref refid="CL BL CP"/>
    </component>
    <part part-id="WG">
        <name>Wing</name>
    </part>
    <part part-id="BL">
        <name>Blaster</name>
    </part>
    <part part-id="CP">
        <name>Cockpit</name>
    </part>
    <part part-id="AM">
        <name>Astro-mech</name>
    </part>
    <part part-id="CL">
        <name>Solar energy collectors</name>
    </part>
</parts-list>