=== Arrrrrr/Hoth/XSLT/templates/resume/resume.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT resume (heading,objective,summary,history,education,specialities)>
    <!ELEMENT heading (name,telephone,email)>
      	<!ELEMENT name (#PCDATA)>
      	<!ELEMENT telephone (#PCDATA)>
      	<!ELEMENT email (#PCDATA)>
    <!ELEMENT objective (#PCDATA)>
    <!ELEMENT summary (skill*)>
      	<!ELEMENT skill (#PCDATA)>
    <!ELEMENT history (experience*)>
        <!ELEMENT experience (title,company,start,end,accomplishments)>
            <!ELEMENT title (#PCDATA)>
            <!ELEMENT company (#PCDATA)>
            <!ELEMENT start (#PCDATA)>
            <!ELEMENT end (#PCDATA)>
            <!ELEMENT accomplishments (accomplishment*)>
                <!ELEMENT accomplishment (#PCDATA)>
    <!ELEMENT education (program)>
        <!ELEMENT program (school,degree)>
            <!ELEMENT school (#PCDATA)>
            <!ELEMENT degree (#PCDATA)>
    <!ELEMENT specialities (speciality*)>
        <!ELEMENT speciality (#PCDATA|tool)*>
            <!ELEMENT tool (#PCDATA)>

=== Arrrrrr/Hoth/XSLT/templates/resume/resume.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resume SYSTEM "resume.dtd">
<resume>
	<heading>
		<name></name>
		<telephone></telephone>
		<email></email>
	</heading>
	<objective></objective>
	<summary>
		<skill></skill>
	</summary>
	<history>
		<experience>
			<title></title>
			<company></company>
			<start></start>
			<end></end>
			<accomplishments>
				<accomplishment>
				</accomplishment>
			</accomplishments>
		</experience>
	</history>
	<education>
		<program>
			<school></school>
			<degree></degree>
		</program>
	</education>
	<specialities>
		<speciality>
			<tool></tool>
		</speciality>
	</specialities>
</resume>
